# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id_livro', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=250, verbose_name='Título')),
                ('autor', models.CharField(max_length=150, verbose_name='Autor')),
                ('editora', models.CharField(blank=True, max_length=150, null=True, verbose_name='Editora')),
                ('ano_publicacao', models.IntegerField(blank=True, null=True, verbose_name='Ano')),
                ('edicao', models.IntegerField(verbose_name='Edição')),
                ('isbn', models.CharField(max_length=13, verbose_name='ISBN')),
                ('sinopse', models.TextField(blank=True, null=True, verbose_name='Sinopse')),
            ],
        ),
    ]
